include:
  - template: Jobs/SAST.gitlab-ci.yml

# This file is a template, and might need editing before it works on your project.
# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/ee/development/cicd/templates.html
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Python.gitlab-ci.yml

# Official language image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/python/tags/
# image: python:latest
image: python:3.8.11

# Change pip's cache directory to be inside the project directory since we can
# only cache local items.
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

# Pip's cache doesn't store the python packages
# https://pip.pypa.io/en/stable/reference/pip_install/#caching
#
# If you want to also cache the installed packages, you have to install
# them in a virtualenv and cache it as well.
cache:
  paths:
    - .cache/pip
    - venv/

before_script:
  - python -V  # Print out python version for debugging
  - pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate

test:
  script:
    - pip install -r requirements-dev.txt
    - copy yeoboseyo/env.sample yeoboseyo/.env
    - cd yeoboseyo
    - python -m pytest -s
    #- pip install tox  # you can also use tox
    #- tox -r  # tox.ini will install flake8 pytest

deploy:
  script:
    - cat $PYPIRC > /tmp/.pypirc
    - pip install twine
    - python setup.py  bdist_wheel
    - python -m twine upload --repository gitlab dist/yeoboseyo-${CI_COMMIT_TAG}-py3-none-any.whl --config-file /tmp/.pypirc
  only:
    - tags
