# You can override the included template(s) by including variable overrides
# SAST customization: https://docs.gitlab.com/ee/user/application_security/sast/#customizing-the-sast-settings
# Secret Detection customization: https://docs.gitlab.com/ee/user/application_security/secret_detection/#customizing-settings
# Dependency Scanning customization: https://docs.gitlab.com/ee/user/application_security/dependency_scanning/#customizing-the-dependency-scanning-settings
# Note that environment variables can be set in several places
# See https://docs.gitlab.com/ee/ci/variables/#cicd-variable-precedence
include:
- template: Jobs/SAST.gitlab-ci.yml
- template: Security/SAST.gitlab-ci.yml
- template: Security/Dependency-Scanning.gitlab-ci.yml
- template: Security/Secret-Detection.gitlab-ci.yml
image: python:3.8.11
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  DS_EXCLUDED_ANALYZERS: bundler-audit, retire.js, gemnasium, gemnasium-maven
cache:
  paths:
  - ".cache/pip"
  - venv/
before_script:
- python -V
- pip install virtualenv
- virtualenv venv
- source venv/bin/activate
test:
  script:
  - pip install -r requirements-dev.txt
  - cp yeoboseyo/env.sample yeoboseyo/.env
  - cd yeoboseyo
  - python -m pytest -s
deploy:
  script:
  - cat $PYPIRC > /tmp/.pypirc
  - cat $PYPIRC_PYPI > /tmp/.pypirc_pypi
  - pip install twine
  - python setup.py bdist_wheel
  - python -m twine upload --repository gitlab dist/* --config-file /tmp/.pypirc
  - python -m twine upload dist/* --config-file /tmp/.pypirc_pypi
  only:
  - tags
stages:
- test
sast:
  variables:
    SAST_EXCLUDED_ANALYZERS: bandit, brakeman, eslint, flawfinder, gosec, kubesec,
      nodejs-scan, phpcs-security-audit, pmd-apex, security-code-scan, sobelow, spotbugs
    SAST_EXCLUDED_PATHS: "venv"
    SAST_SEMGREP_METRICS: "false"
  stage: test
